server:
  port: 9002
spring:
  #redis数据库连接设置
  redis:
    host: 121.89.177.244
    port: 6379
    database: 0
    timeout: 1800000
    password: 22446688
    lettuce:
      pool:
        max-active: 20
        max-wait: 1
  application:
    name: service-test-9001
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.89.177.244:3306/testDemon?useUnicode=true&characterEncoding=UTF-8
    password: 22446688
    username: root
    #返回的json数据全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:MM:SS
    time-zone: GMT+8
#    nacos注册
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848


#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#  <!--#配置mapper xml文件路径-->,必须pom.xml进行配置后使用
mybatis-plus:
  mapper-locations: classpath:com/plxcc/eduservice/mapper/xml/*.xml  #xml的路径
#开启熔断机制
feign:
  hystrix:
    enabled: true
